@startuml
!theme mars

title Merchant retrieve details of a previously made payment with an invalid payment id
skinparam sequenceMessageAlign center
hide footbox
actor merchant

participant "Payment Gateway" as PaymentGateway
database PaymentRepository

merchant -> PaymentGateway : Send invalid unique payment identifier
activate PaymentGateway #6C8EBF
PaymentGateway -> PaymentGateway : Validate unique payment identifier
PaymentGateway -> merchant : Return response (Error message)
deactivate PaymentGateway

@enduml